app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
# Route de FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /rp_backend  # <-- change this value